#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  7 21:50:00 2021

@author: macbook
"""

from tkinter import *
from PIL import ImageTk, Image
from tkinter import filedialog

root = Tk()
root.title("Planet Encyclopedia")
root.geometry("500x500")
root.config(bg="navy")

label_popsicle_image = Label(root,bg="purple", highlightthickness=5,)
label_popsicle_image.place(relx=0.5,rely=0.9,anchor = CENTER)
img_path = ""

def OpenImage():
    img_path = filedialog.askopenfilename(title="Open Text File",filetypes=[("Image Files","*.jpg:*.gif;*.jpg;*.png;*.txt;")])
    label_popsicle_image["image"]= img
    print(img_path)
    imge = ImageTk.PhotoImage(Image.open ("cute_popsicle.jpg"))
    img.close()
    
    btn = Button(root, text="Open Image" , command=OpenImage(),font=("Baskerville Old Face",18,"bold"),bg="white")
    btn.place(relx=0.2, rely=0.18, anchor=CENTER)
root.mainloop()

